-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table company (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  constraint pk_company primary key (id)
);

create table crop (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  introduced                    timestamp,
  discontinued                  timestamp,
  company_id                    bigint,
  user_id                       bigint,
  constraint pk_crop primary key (id)
);

create table field (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  north_east_latitude           double,
  north_east_longitude          double,
  south_west_latitude           double,
  south_west_longitude          double,
  user_id                       bigint,
  constraint pk_field primary key (id)
);

create table app_user (
  id                            bigint generated by default as identity not null,
  username                      varchar(255),
  email                         varchar(255),
  password                      varchar(255),
  constraint pk_app_user primary key (id)
);

-- foreign keys and indices
create index ix_crop_company_id on crop (company_id);
alter table crop add constraint fk_crop_company_id foreign key (company_id) references company (id) on delete restrict on update restrict;

create index ix_crop_user_id on crop (user_id);
alter table crop add constraint fk_crop_user_id foreign key (user_id) references app_user (id) on delete restrict on update restrict;

create index ix_field_user_id on field (user_id);
alter table field add constraint fk_field_user_id foreign key (user_id) references app_user (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table crop drop constraint if exists fk_crop_company_id;
drop index if exists ix_crop_company_id;

alter table crop drop constraint if exists fk_crop_user_id;
drop index if exists ix_crop_user_id;

alter table field drop constraint if exists fk_field_user_id;
drop index if exists ix_field_user_id;

-- drop all
drop table if exists company;

drop table if exists crop;

drop table if exists field;

drop table if exists app_user;

