-- Add soil diagnostic table

-- !Ups

create table soil_diagnostic (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp,
  updated_at                    timestamp,
  diagnostic_date               date,
  field_id                      bigint,
  user_id                       bigint,
  cec                           decimal(10,3),
  ec                            decimal(10,3),
  ph_h2o                        decimal(5,2),
  ph_kcl                        decimal(5,2),
  nh4_n                         decimal(10,3),
  k2o                           decimal(10,3),
  phosphorus_absorption_coefficient decimal(10,3),
  available_nitrogen            decimal(10,3),
  p2o5                          decimal(10,3),
  ca_o                          decimal(10,3),
  no3_n                         decimal(10,3),
  humus                         decimal(10,3),
  mg_o                          decimal(10,3),
  constraint pk_soil_diagnostic primary key (id)
);

-- foreign keys and indices
create index ix_soil_diagnostic_field_id on soil_diagnostic (field_id);
alter table soil_diagnostic add constraint fk_soil_diagnostic_field_id foreign key (field_id) references field (id) on delete restrict on update restrict;

create index ix_soil_diagnostic_user_id on soil_diagnostic (user_id);
alter table soil_diagnostic add constraint fk_soil_diagnostic_user_id foreign key (user_id) references app_user (id) on delete restrict on update restrict;

-- !Downs

-- drop foreign keys
alter table if exists soil_diagnostic drop constraint if exists fk_soil_diagnostic_field_id;
drop index if exists ix_soil_diagnostic_field_id;

alter table if exists soil_diagnostic drop constraint if exists fk_soil_diagnostic_user_id;
drop index if exists ix_soil_diagnostic_user_id;

-- drop table
drop table if exists soil_diagnostic cascade;