# User authentication schema

# --- !Ups
create table user (
  id                            bigint generated by default as identity not null,
  username                      varchar(255) not null,
  email                         varchar(255) not null,
  password                      varchar(255) not null,
  constraint pk_user primary key (id),
  constraint uq_user_username unique (username),
  constraint uq_user_email unique (email)
);

-- Add user relationship to crop table
alter table crop add column user_id bigint;
create index ix_crop_user_id on crop (user_id);
alter table crop add constraint fk_crop_user_id foreign key (user_id) references user (id) on delete restrict on update restrict;

# --- !Downs

-- Remove user relationship from crop table
alter table crop drop constraint if exists fk_crop_user_id;
drop index if exists ix_crop_user_id;
alter table crop drop column if exists user_id;

-- Drop user table
drop table if exists user;