-- Add Field table for field (圃場) management

-- !Ups

-- apply changes
create table field (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  north_east_latitude           double precision,
  north_east_longitude          double precision,
  south_west_latitude           double precision,
  south_west_longitude          double precision,
  user_id                       bigint,
  constraint pk_field primary key (id)
);

-- foreign keys and indices
create index ix_field_user_id on field (user_id);
alter table field add constraint fk_field_user_id foreign key (user_id) references app_user (id) on delete restrict on update restrict;

-- !Downs

-- drop all foreign keys
alter table field drop constraint if exists fk_field_user_id;
drop index if exists ix_field_user_id;

-- drop all
drop table if exists field;