# Add pesticide registration table

# --- !Ups

CREATE TABLE pesticide_registration (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp,
  updated_at                    timestamp,
  registration_number           varchar(255),
  usage                         varchar(255),
  pesticide_type                varchar(255),
  pesticide_name                varchar(255),
  abbreviation                  varchar(255),
  crop_name                     varchar(255),
  application_location          varchar(255),
  target_pest_disease           varchar(500),
  purpose                       varchar(255),
  dilution_amount               varchar(500),
  constraint pk_pesticide_registration primary key (id)
);

# --- !Downs

DROP TABLE IF EXISTS pesticide_registration;